group: container
language: node_js
cache:
  directories:
    - node_modules

stages:
  - test
  - name: build
    if: type = push AND branch = main

jobs:
  include:
    - stage: test
      script: npm run test
      env:
        - JOB_NAME=tests
    - script: npm run lint
      env:
        - JOB_NAME=linters
    - stage: build
      script: npm run build
      env:
        - JOB_NAME=build
